# Generated by Django 5.1 on 2025-08-03 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_multiple_votes', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_polls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.poll')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.polloption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['created_at'], name='polls_poll_created_3f3b19_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['expires_at'], name='polls_poll_expires_0c4433_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['is_active'], name='polls_poll_is_acti_53c655_idx'),
        ),
        migrations.AddIndex(
            model_name='polloption',
            index=models.Index(fields=['poll'], name='polls_pollo_poll_id_9abd98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='polloption',
            unique_together={('poll', 'text')},
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['user', 'option'], name='polls_vote_user_id_1ac8c7_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['voted_at'], name='polls_vote_voted_a_cca77e_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['option'], name='polls_vote_option__9fc1fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'option')},
        ),
    ]
