# Generated by Django 5.1 on 2025-08-06 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vote',
            name='polls_vote_user_id_1ac8c7_idx',
        ),
        migrations.RemoveIndex(
            model_name='vote',
            name='polls_vote_voted_a_cca77e_idx',
        ),
        migrations.RemoveIndex(
            model_name='vote',
            name='polls_vote_option__9fc1fb_idx',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vote',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.student'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'option'), name='unique_user_vote'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('student', 'option'), name='unique_student_vote'),
        ),
    ]
